import type { NormalizedJiraIssue } from "../jira/jira.types.js";
import type { SlackBlock, SlackMessage } from "./slack.client.js";
import type { WorkspaceSnapshot } from "../workspace/workspace.manager.js";

export class SlackFormatter {
  initial(issue: NormalizedJiraIssue): SlackMessage { return { text: `Jira investigation started: ${issue.key} — ${issue.summary}`, blocks: [{ type: "header", text: { type: "plain_text", text: "🔎 Jira investigation started" } }, { type: "section", text: { type: "mrkdwn", text: `*${issue.key} — ${issue.summary}*` }, fields: [{ type: "mrkdwn", text: "*Status*\nInvestigating" }, { type: "mrkdwn", text: `*Priority*\n${issue.priority ?? "Not set"}` }, { type: "mrkdwn", text: `*Reporter*\n${issue.reporter ?? "Unassigned"}` }, { type: "mrkdwn", text: `*Assignee*\n${issue.assignee ?? "Unassigned"}` }] }, { type: "context", elements: [{ type: "mrkdwn", text: "Reply in this thread to ask follow-up questions." }] }] }; }
  progress(question: string | null): SlackMessage { return { text: "Investigation in progress", blocks: [{ type: "header", text: { type: "plain_text", text: "🔍 Investigation in progress" } }, { type: "section", text: { type: "mrkdwn", text: question ? `*Question*\n${question}` : "Preparing workspaces and tracing the relevant code path." } }] }; }
  runControls(input: { investigationId: string; issueKey: string; summary: string }): SlackMessage { return { text: `Codex is working on ${input.issueKey}`, blocks: [{ type: "section", text: { type: "mrkdwn", text: `*⏳ Codex is working*\n${input.issueKey} — ${input.summary}` } }, { type: "actions", block_id: `control-${input.investigationId}`, elements: [{ type: "button", text: { type: "plain_text", text: "Stop" }, style: "danger", action_id: "investigation_stop", value: input.investigationId, confirm: { title: { type: "plain_text", text: "Stop this investigation?" }, text: { type: "mrkdwn", text: "Codex will stop at the next safe interruption point. You can continue later." }, confirm: { type: "plain_text", text: "Stop" }, deny: { type: "plain_text", text: "Keep working" } } }] }] }; }
  stopping(issueKey: string): SlackMessage { return { text: `Stopping ${issueKey}`, blocks: [{ type: "section", text: { type: "mrkdwn", text: `*⏳ Stopping ${issueKey}…*\nWaiting for Codex to finish its current safe operation.` } }] }; }
  pausedControls(input: { investigationId: string; issueKey: string; reason?: string }): SlackMessage { return { text: `${input.issueKey} paused`, blocks: [{ type: "section", text: { type: "mrkdwn", text: `*⏸ Investigation paused*\n${input.reason ?? "Codex was stopped. You can continue from the saved investigation context or dismiss it."}` } }, { type: "actions", block_id: `paused-${input.investigationId}`, elements: [{ type: "button", text: { type: "plain_text", text: "Continue" }, style: "primary", action_id: "investigation_continue", value: input.investigationId }, { type: "button", text: { type: "plain_text", text: "Dismiss" }, style: "danger", action_id: "investigation_dismiss", value: input.investigationId, confirm: { title: { type: "plain_text", text: "Dismiss investigation?" }, text: { type: "mrkdwn", text: "This cancels queued work. Existing worktree changes are retained but Codex will not continue automatically." }, confirm: { type: "plain_text", text: "Dismiss" }, deny: { type: "plain_text", text: "Keep paused" } } }] }] }; }
  resuming(issueKey: string): SlackMessage { return { text: `${issueKey} resuming`, blocks: [{ type: "section", text: { type: "mrkdwn", text: `*▶️ Continuing investigation*\n${issueKey} was queued to resume from the saved Codex context.` } }] }; }
  dismissed(issueKey: string): SlackMessage { return { text: `${issueKey} dismissed`, blocks: [{ type: "section", text: { type: "mrkdwn", text: `*🛑 Investigation dismissed*\n${issueKey} will not continue automatically. Existing isolated worktrees were retained.` } }] }; }
  finishedControls(issueKey: string): SlackMessage { return { text: `${issueKey} finished`, blocks: [{ type: "context", elements: [{ type: "mrkdwn", text: `✅ ${issueKey} run finished` }] }] }; }
  complete(issue: NormalizedJiraIssue, result: string, sources: WorkspaceSnapshot[] = []): SlackMessage {
    return { text: `Investigation complete: ${issue.key} — ${issue.summary}`, blocks: [{ type: "header", text: { type: "plain_text", text: "✅ Investigation complete" } }, { type: "section", text: { type: "mrkdwn", text: `*${issue.key} — ${issue.summary}*` } }, { type: "divider" }, { type: "section", text: { type: "mrkdwn", text: toSlackEvidence(result, sources).slice(0, 2_900) || "No findings were returned." } }, { type: "context", elements: [{ type: "mrkdwn", text: "Source evidence is pinned to the ticket worktree snapshot. Full details are preserved in the investigation workspace." }] }] };
  }
  approval(input: { issueKey: string; summary: string; approvalId: string; question: string; expiresAt: Date; scope: "PATCH" | "COMMIT" | "PUSH" }): SlackMessage {
    const details = input.scope === "PUSH" ? { action: "create a patch, commit it, and push the ticket branch to origin", scope: "Ticket worktree and its remote ticket branch", button: "Approve change and push", confirmation: "Codex may modify the ticket worktree, commit, and push only its ticket branch. It cannot force-push." } : input.scope === "COMMIT" ? { action: "create a patch and commit it on the ticket branch", scope: "Ticket worktree and local ticket branch", button: "Approve change and commit", confirmation: "Codex may modify the ticket worktree and create a local commit. It cannot push." } : { action: "create a patch in this ticket's isolated worktree", scope: "Ticket worktree only", button: "Approve write access", confirmation: "Codex may modify only this ticket's isolated Git worktree. It cannot commit or push." };
    const blocks: SlackBlock[] = [{ type: "header", text: { type: "plain_text", text: "🟠 Approval required" } }, { type: "section", text: { type: "mrkdwn", text: `*${input.issueKey} — ${input.summary}*\n\n*Requested action*\nAllow Codex to ${details.action}.\n\n*Request*\n${input.question.slice(0, 1_500)}` } }, { type: "section", fields: [{ type: "mrkdwn", text: `*Scope*\n${details.scope}` }, { type: "mrkdwn", text: `*Expires*\n<!date^${Math.floor(input.expiresAt.getTime() / 1_000)}^{date_short_pretty} at {time}|soon>` }] }, { type: "actions", block_id: `approval-${input.approvalId}`, elements: [{ type: "button", text: { type: "plain_text", text: details.button }, style: "primary", action_id: "approval_approve", value: input.approvalId, confirm: { title: { type: "plain_text", text: `${details.button}?` }, text: { type: "mrkdwn", text: details.confirmation }, confirm: { type: "plain_text", text: "Approve" }, deny: { type: "plain_text", text: "Cancel" } } }, { type: "button", text: { type: "plain_text", text: "Reject" }, style: "danger", action_id: "approval_reject", value: input.approvalId }] }];
    return { text: `Approval required for ${input.issueKey}`, blocks };
  }
  approvalDecided(approved: boolean, approver: string): SlackMessage { return { text: approved ? "Write access approved" : "Write access rejected", blocks: [{ type: "header", text: { type: "plain_text", text: approved ? "✅ Write access approved" : "⛔ Write access rejected" } }, { type: "section", text: { type: "mrkdwn", text: approved ? `Approved by <@${approver}>. Codex will continue in the isolated ticket worktree.` : `Rejected by <@${approver}>. The investigation remains read-only.` } }] }; }
  error(reason: string): SlackMessage { return { text: `Investigation failed: ${reason}`, blocks: [{ type: "header", text: { type: "plain_text", text: "⚠️ Investigation failed" } }, { type: "section", text: { type: "mrkdwn", text: `*Reason*\n${reason.slice(0, 2_800)}` } }] }; }
}

/** Converts Codex Markdown into Slack mrkdwn without leaking unusable local paths. */
export function toSlackEvidence(result: string, sources: WorkspaceSnapshot[]): string {
  let formatted = result.replace(/\*\*([^*\n]+)\*\*/g, "*$1*").replace(/\\-/g, "-");
  for (const source of [...sources].sort((left, right) => right.workspacePath.length - left.workspacePath.length)) {
    const prefix = escapeRegex(`${source.workspacePath}/`);
    const expression = new RegExp(`\\[([^\\]]+)\\]\\(${prefix}([^):]+)(?::(\\d+))?\\)`, "g");
    formatted = formatted.replace(expression, (_match, label: string, relativePath: string, line: string | undefined) => {
      const fallback = `*${cleanLabel(label)}* — \`${source.repositoryName}/${relativePath}${line ? `:${line}` : ""}\``;
      const url = source.sourceUrlTemplate ? sourceUrl(source.sourceUrlTemplate, source.commitSha, relativePath, line) : undefined;
      return url ? `<${url}|${cleanLabel(label)}>` : fallback;
    });
  }
  return formatted.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, (_match, label: string, url: string) => `<${url}|${cleanLabel(label)}>`);
}

function sourceUrl(template: string, ref: string, relativePath: string, line?: string): string {
  const encodedPath = relativePath.split("/").map(encodeURIComponent).join("/");
  const file = relativePath.split("/").at(-1) ?? relativePath;
  const withoutLineAnchor = line ? template : template.replace(/#L\{line\}|#\{file\}-\{line\}|#lines-\{line\}/g, "");
  return withoutLineAnchor.replaceAll("{ref}", encodeURIComponent(ref)).replaceAll("{path}", encodedPath).replaceAll("{file}", encodeURIComponent(file)).replaceAll("{line}", line ? encodeURIComponent(line) : "");
}
function cleanLabel(value: string): string { return value.replace(/[|>]/g, "").trim(); }
function escapeRegex(value: string): string { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
